// ***********************************************************************
// ** Title.........:    TinyMce polish lang. Plugins: media/pl_dlg.js
// ** Version.......:    1.4
// ** Author........:    Stefan Wajda <zwiastun@zwiastun.net>
// ** Filename......:    pl.php (polish language file)
// ** Last changed..:    16/6/2006, 5/3/2011
// ***********************************************************************/

tinyMCE.addI18n('pl.media_dlg',{
title:"Wstaw/Dostosuj media",
general:"Podstawowe",
advanced:"Rozszerzone",
file:"Plik/Adres",
list:"Lista",
size:"Wymiary",
preview:"Podgląd",
constrain_proportions:"Zachowaj proporcje",
type:"Typ",
id:"Id",
name:"Nazwa",
class_name:"Klasa",
vspace:"Odstępy nad i pod",
hspace:"Odstępy obok",
play:"Autoodtwarzanie",
loop:"Powtarzaj",
menu:"Pokaż menu",
quality:"Jakość",
scale:"Skala",
align:"Wyrównanie",
salign:"Dopasowanie",
wmode:"Tryb okna",
bgcolor:"Kolor tła",
base:"Adres bazowy",
flashvars:"Zmienne Flash - Flashvars",
liveconnect:"SWLiveConnect",
autohref:"AutoHREF",
cache:"Pamięć podręczna",
hidden:"Ukrycie",
controller:"Kontroler dźwięku",
kioskmode:"Tryb kiosku",
playeveryframe:"Odtwarzaj każdą klatkę",
targetcache:"Target cache",
correction:"Bez korekcji",
enablejavascript:"Włącz JavaScript",
starttime:"Czas rozpoczęcia",
endtime:"Czas zakończenia",
href:"Adres",
qtsrcchokespeed:"Zmniejsz tempo",
target:"Cel",
volume:"Głośność",
autostart:"Auto start",
enabled:"Włączone",
fullscreen:"Pełny ekran",
invokeurls:"Zdalny URL",
mute:"Wycisz",
stretchtofit:"Rozciągnij, aby dopasować",
windowlessvideo:"Okno wideo",
balance:"Balans",
baseurl:"URL bazowy",
captioningid:"Id podpisu",
currentmarker:"Oznacz aktualne",
currentposition:"Aktualna pozycja",
defaultframe:"Domyślna ramka",
playcount:"Liczba powtórzeń",
rate:"Tempo",
uimode:"UI Mode",
flash_options:"Opcje Flasha",
qt_options:"Opcje Quicktime",
wmp_options:"Opcje Windows media",
rmp_options:"Opcje Real media",
shockwave_options:"Opcje Shockwave",
autogotourl:"Automatycznie skocz pod adres",
center:"Środek",
imagestatus:"Stan grafiki",
maintainaspect:"Zachowaj ustawienie",
nojava:"Bez Java",
prefetch:"Przeładuj",
shuffle:"Losuj",
console:"Konsola",
numloop:"Liczba powtórzeń",
controls:"Kontrola",
scriptcallbacks:"Funkcje zwrotne skryptu",
swstretchstyle:"Styl rozciągnięcia",
swstretchhalign:"Rozciągnij w poziomie",
swstretchvalign:"Rozciągnij w pionie",
sound:"Dźwięk",
progress:"Postęp",
qtsrc:"QT Src",
qt_stream_warn:"Źródła mediów strumieniowych rtsp mogą być dodane do pola QT na karcie opcji rozszerzonych.\nW polu SRC możesz również dodać niestrumieniowe wersję medium.",
align_top:"Góra",
align_right:"Prawa",
align_bottom:"Dół",
align_left:"Lewa",
align_center:"Środek",
align_top_left:"Góra lewa",
align_top_right:"Góra prawa",
align_bottom_left:"Dół lewa",
align_bottom_right:"Dół prawa",
flv_options:"Opcje filmików Flasha",
flv_scalemode:"Tryb skalowania",
flv_buffer:"Bufor",
flv_startimage:"Obrazek startowy",
flv_starttime:"Czas rozpoczęcia",
flv_defaultvolume:"Domyślna głośność",
flv_hiddengui:"Ukryty GUI",
flv_autostart:"Auto start",
flv_loop:"Powtarzaj",
flv_showscalemodes:"Pokaż tryby skali",
flv_smoothvideo:"Płynne odtwarzanie wideo",
flv_jscallback:"Funkcja zwrotna JS"
});