// ***********************************************************************
// ** Title.........:    TinyMCE polish lang. Plugins: table
// ** Version.......:    1.0
// ** Author........:    Stefan Wajda <zwiastun@zwiastun.net>,
// ** Filename......:    pl.js (polish language file)
// ** Last changed..:    13/06/2006, 13 marca 2011, 6 maja 2011, 22 maja 2011
// ***********************************************************************/
tinyMCE.addI18n('pl.table_dlg',{
general_tab:"Podstawowe",
advanced_tab:"Rozszerzone",
general_props:"Podstawowe właściwości",
advanced_props:"Rozszerzone właściwości",
rowtype:"Wiersz w części tabeli",
title:"Wstaw/Dostosuj tabelę",
width:"Szerokość",
height:"Wysokość",
cols:"Kolumny",
rows:"Wiersze",
cellspacing:"Odstęp&nbsp;między komórkami",
cellpadding:"Odstęp&nbsp;wewnątrz komórek",
border:"Obramowanie",
align:"Wyrównanie",
align_default:"Domyślnie",
align_left:"Do lewej",
align_right:"Do prawej",
align_middle:"Wyśrodkuj",
row_title:"Właściwości wiersza",
cell_title:"Właściwości komórki",
cell_type:"Typ komórki",
valign:"Wyrównanie pionowe",
align_top:"do góry",
align_bottom:"do dołu",
bordercolor:"Kolor obramowania",
bgcolor:"Kolor tła",
merge_cells_title:"Scal komórki",
id:"Id",
style:"Styl CSS",
langdir:"Kierunek języka",
langcode:"Kod języka",
mime:"Typ MIME",
ltr:"Od lewej do prawej",
rtl:"Od prawej do lewej",
bgimage:"Obrazek tła",
summary:"Streszczenie",
td:"Dane",
th:"Nagłówek",
cell_cell:"Dostosuj bieżącą komórkę",
cell_row:"Dostosuj wszystkie komórki w rzędzie",
cell_all:"Dostosuj wszystkie komórki w tabeli",
row_row:"Dostosuj bieżący wiersz",
row_odd:"Dostosuj nieparzyste wiersze",
row_even:"Dostosuj parzyste wiersze",
row_all:"Dostosuj wszystkie wiersze",
thead:"Nagłówek tabeli",
tbody:"Środek tabeli",
tfoot:"Stopka tabeli",
scope:"Zakres",
rowgroup:"Grupuj wiersze",
colgroup:"Grupuj kolumny",
col_limit:"Osiągnięto już maksymalną liczbę kolumn {$cols}.",
row_limit:"Osiągnięto już maksymalną liczbę wierszy {$rows}.",
cell_limit:"Osiągnięto już maksymalną liczbę komórek {$cells}.",
missing_scope:"Czy na pewno chcesz kontynuować bez określenia zakresu komórek obejmowanych nagłówkiem. Bez podania tej informacji zrozumienie zawartości tabeli może być trudne np. dla osób niewidzących, korzystających ze specjalistycznego oprogramowania odczytującego treść tabeli.",
caption:"Podpis tabeli",
frame:"Obramowanie",
frame_none:"brak",
frame_groups:"pomiędzy grupami",
frame_rows:"pomiędzy wierszami",
frame_cols:"pomiędzy kolumnami",
frame_all:"wszystkie",
rules:"Linie wewnętrzne",
rules_void:"bez linii",
rules_above:"górny brzeg",
rules_below:"dolny brzeg",
rules_hsides:"górny i dolny brzeg",
rules_lhs:"lewy brzeg",
rules_rhs:"prawy brzeg",
rules_vsides:"lewy i prawy brzeg",
rules_box:"wszystkie brzegi",
rules_border:"otoczka"
});