// ***********************************************************************
// ** Title.........:    TinyMce polish lang. Plugins:themes/advanced/pl_dlg.js
// ** Version.......:    1.4
// ** Author........:    Stefan Wajda <zwiastun@zwiastun.net>
// ** Filename......:    pl.php (polish language file)
// ** Last changed..:    16/6/2006, 5/3/2011  / 13 marca 2011
// ***********************************************************************/
tinyMCE.addI18n('pl.advanced_dlg',{
about_title:"O TinyMCE",
about_general:"O ",
about_help:"Pomoc",
about_license:"Licencja",
about_plugins:"Dodatki",
about_plugin:"Dodatek",
about_author:"Autor",
about_version:"Wersja",
about_loaded:"Wczytane dodatki",
anchor_title:"Wstaw/Dostosuj zakładkę",
anchor_name:"Nazwa zakładki",
code_title:"Edytor HTML",
code_wordwrap:"Zawijanie wierszy",
colorpicker_title:"Wskaż kolor",
colorpicker_picker_tab:"Próbnik",
colorpicker_picker_title:"Próbnik kolorów",
colorpicker_palette_tab:"Paleta",
colorpicker_palette_title:"Paleta kolorów",
colorpicker_named_tab:"Nazwa",
colorpicker_named_title:"Nazwa koloru",
colorpicker_color:"Kolor:",
colorpicker_name:"Nazwa:",
charmap_title:"Wybierz znak",
image_title:"Wstaw/Dostosuj obrazek",
image_src:"Adres obrazka",
image_alt:"Opis obrazka",
image_list:"Lista obrazków",
image_border:"Obramowanie",
image_dimensions:"Wymiary",
image_vspace:"Odstępy nad i pod",
image_hspace:"Odstępy obok",
image_align:"Wyrównanie",
image_align_baseline:"Linia bazowa",
image_align_top:"Góra",
image_align_middle:"Środek",
image_align_bottom:"Dół",
image_align_texttop:"Góra tekstu",
image_align_textbottom:"Dół tekstu",
image_align_left:"Do lewej",
image_align_right:"Do prawej",
link_title:"Wstaw/Dostosuj odnośnik",
link_url:"Adres odnośnika",
link_target:"Otwórz w",
link_target_same:"Otwórz w tym samym oknie",
link_target_blank:"Otwórz w nowym oknie",
link_titlefield:"Tytuł",
link_is_email:"Podane łącze wydaje się być adresem pocztowym - czy dodać protokół: mailto:?",
link_is_external:"Podane łącze wydaje się być zewnętrznym adresem internetowym - czy dodać protokół http://?",
link_list:"Lista odnośników"
});